### ISSUE TITLE
Adding Brave

### ISSUE THREAD

**Issue by Yoannjap** [neoblackxt/AnyWebView#10]
Hey, your module is brilliant!

Maya you add Brave support to it?

Thanks a lot.

Yoannjap

**Comment by neoblackxt** [comment]
This problem may be a bit complicated. If a browser or system webview is supported, it must meet the requirements that it has implemented some interfaces, such as libtrichrome or libmonochrome, and clarify the classes that implement these interfaces in the Manifest file.Otherwise, it cannot be set as a system webview implementation.

**Comment by neoblackxt** [comment]
TL;DR Brave won't be supported for it own reasons. You may need to contact the Brave developers and ask them to add the relevant features.
